# Install biocorecrg/falco:20b2a85
FROM ubuntu:focal-20211006

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

ARG HTSLIB_VERSION=1.16
ARG FALCO_VERSION=20b2a85


#upgrade pip
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt install -y git zlib1g zlib1g-dev wget libbz2-dev liblzma-dev 
RUN wget https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2
RUN tar -jvxf htslib-${HTSLIB_VERSION}.tar.bz2; cd htslib-${HTSLIB_VERSION}; ./configure; make; make install

RUN git clone https://github.com/smithlabcode/falco.git;
RUN cd falco; git checkout ${FALCO_VERSION}; make HAVE_HTSLIB=1 all; make HAVE_HTSLIB=1 install
RUN mv /falco/bin/falco /usr/local/bin/

#RUN tar -zvxf falco-${FALCO_VERSION}.tar.gz; cd falco-${FALCO_VERSION}; ./configure CXXFLAGS="-O3 -Wall" --enable-hts; make all; make install 
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"


# Clean cache
#RUN yum clean all 

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

