# Install biocorecrg/racon:1.5.0:
FROM ubuntu:22.04

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

ARG HTSLIB_VERSION=1.18
ARG SAMTOOOLS_VERSION=1.18
ARG MINIMAP2_VERSION=2.26
ARG RACON_VERSION=1.5.0

#upgrade pip
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt install -y procps git zlib1g zlib1g-dev wget libbz2-dev liblzma-dev 

#Install HTSLIB
RUN wget https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2
RUN tar -jvxf htslib-${HTSLIB_VERSION}.tar.bz2; cd htslib-${HTSLIB_VERSION}; ./configure; make; make install
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"

#Install SAMTOOLS
RUN apt-get install -y libncurses-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN wget https://github.com/samtools/samtools/releases/download/${SAMTOOOLS_VERSION}/samtools-${SAMTOOOLS_VERSION}.tar.bz2
RUN tar -jvxf samtools-${SAMTOOOLS_VERSION}.tar.bz2; cd samtools-${SAMTOOOLS_VERSION}; ./configure; make; make install

#Install MINIMAP2
RUN wget https://github.com/lh3/minimap2/releases/download/v2.26/minimap2-${MINIMAP2_VERSION}_x64-linux.tar.bz2
RUN tar -jvxf minimap2-${MINIMAP2_VERSION}_x64-linux.tar.bz2;  
RUN mv minimap2-${MINIMAP2_VERSION}_x64-linux/minimap2 /usr/local/bin

#Install RACON
RUN wget https://github.com/lbcb-sci/racon/archive/refs/tags/${RACON_VERSION}.tar.gz;
RUN tar -zvxf ${RACON_VERSION}.tar.gz;
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y cmake libboost-all-dev
RUN cd racon-${RACON_VERSION}; mkdir build; cd build; cmake .. && make
#RUN cd racon-${RACON_VERSION}; mkdir build; cd build; cmake -DCMAKE_CXX_FLAGS="-mno-avx2" -DCMAKE_BUILD_TYPE=Release .. && make
ENV PATH="$PATH:/racon-${RACON_VERSION}/build/bin"

# Clean cache
RUN rm -fr *.tar.bz2; rm -fr *.tar.gz; rm -fr samtools-* htslib-* minimap2*   
RUN yum clean all 

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

