FROM rocker/r-base:4.0.3

LABEL authors="Luca Cozzuto <lucacozzuto@gmail.com>"

#RUN apt-get update; apt-get upgrade -y
RUN apt-get update
RUN apt-get install -y libssl-dev  libcurl4-openssl-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y procps

COPY ./deps.R /tmp

RUN Rscript /tmp/deps.R

# install_github('rreybeyb/MoAIMS/codes')"
#RUN set -x; rm -rf /var/lib/apt/lists/*

