FROM biocorecrg/centos-perlbrew-pyenv

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

ARG SAMTOOLS_VERSION=1.4.1
ARG EPIC_VERSION=0.2.12
ARG JELLYFISH_VERSION=2.2.10

#upgrade pip
RUN pip install --upgrade pip


#INSTALLING JELLYFISH
RUN bash -c 'curl -k -L https://github.com/gmarcais/Jellyfish/releases/download/v${JELLYFISH_VERSION}/jellyfish-linux > jellyfish'
RUN chmod +x jellyfish; mv jellyfish /usr/local/bin/; cd ..

# Installing samtools
RUN yum install -y xz-devel.x86_64
RUN bash -c 'curl -k -L https://downloads.sourceforge.net/project/samtools/samtools/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2 > samtools.tar.bz2'
RUN tar -jvxf samtools.tar.bz2
RUN cd samtools-${SAMTOOLS_VERSION}; ./configure; make; make install; cd ../ 

#INSTALLING EPIC
RUN pip install Cython
RUN pip install bioepic==${EPIC_VERSION}

# Clean cache
RUN yum clean all 

#chmod
RUN chmod +x /usr/local/bin/*

#cleaning
RUN rm -fr *.tar.gz; rm -fr *.bz2
