#This will do biocorecrg/nanoplot:1.42.0
FROM biocorecrg/almalinux-perlbrew-pyenv3:9


# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com>

ARG NANOPLOT_VERSION=1.42.0

#upgrade pip
RUN pip install --upgrade pip


#install Nanoplot
RUN pip install pandas
RUN pip install NanoPlot==${NANOPLOT_VERSION}

# Installing GraphicsMagick
RUN yum install -y GraphicsMagick.x86_64


# Clean cache
RUN yum clean all

#cleaning
RUN rm -fr *.tar.gz; rm -fr *.bz2; rm -fr ./tmp
RUN rm -rf /var/cache/yum

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8


