# Install biocorecrg/falco:1.1.0
FROM ubuntu:focal-20211006

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

ARG HTSLIB_VERSION=1.16
ARG FALCO_VERSION=1.1.0

#upgrade pip
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt install -y zlib1g zlib1g-dev wget libbz2-dev liblzma-dev
RUN wget https://github.com/smithlabcode/falco/releases/download/v${FALCO_VERSION}/falco-${FALCO_VERSION}.tar.gz
RUN wget https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2
RUN tar -jvxf htslib-${HTSLIB_VERSION}.tar.bz2; cd htslib-${HTSLIB_VERSION}; ./configure; make; make install
RUN tar -zvxf falco-${FALCO_VERSION}.tar.gz; cd falco-${FALCO_VERSION}; ./configure CXXFLAGS="-O3 -Wall" --enable-hts; make all; make install 
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"


# Clean cache
#RUN yum clean all 

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

