# This will do biocorecrg/pod5:0.2.4 

FROM mambaorg/micromamba:1.5

# Install procps to get 'ps' command
USER root

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

USER $MAMBA_USER

COPY --chown=$MAMBA_USER:$MAMBA_USER environment_0.2.4.yml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes
RUN rm /tmp/env.yaml

ENV PATH /opt/conda/bin:$PATH

