# This will do biocorecrg/pod5:0.3.11 

FROM mambaorg/micromamba:1.5
COPY --chown=$MAMBA_USER:$MAMBA_USER environment_0.3.11.yml  /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes
RUN rm /tmp/env.yaml
ENV PATH /opt/conda/bin:$PATH

